### ISSUE TITLE
I can't download frame of satnogs

### ISSUE THREAD

**Issue by leonelce3t** [alicjamusial/quetzal1-satnogs#1]
Hi!
I can't download SatNOGS decoded frames from Quetzal-1 satellite. I have my station's api, but I don't know what the problem is when I run run.py

I'm using
`$ python3 run.py Authorization: Token ########################## [2020-07-06T01:08:50Z] [2020-07-06T01:14:12Z]
`
Observation: The only doubt is that I have my station offline and I'm selecting a different observation to my station.

Thanks for your attention!!!

**Comment by alicjamusial** [comment]
Hello, what error do you get? 
Please try running the command in the form: `python3 run.py ########################## 2020-07-06T01:08:50Z 2020-07-06T01:14:12Z`

**Comment by leonelce3t** [comment]
Thanks

using that line, I have that answer:

~/quetzal1-satnogs-master$ python3 run.py ###################### 2020-07-06T01:08:50Z 2020-07-06T01:14:12Z
The token is invalid. Try again.

**Comment by leonelce3t** [comment]
Excuse me, I already solved the problem, it effectively worked with:
`python3 run.py ############################ 2020-07-06T01:08:50Z 2020-07-06T01:14:12Z`
The API Key **SatNOGS DB** is different from API Key of ground station.

Thanks!!!

**Comment by alicjamusial** [comment]
Oh, yes, it is :) I'm glad it works! :tada:
